### ISSUE TITLE
Issue with #

### ISSUE THREAD

**Issue by m007** [ilogue/docker.lang#10]
Currently a line like

    RUN sed -i 's/#dbms.shell.enabled=true/dbms.shell.enabled=true/' /var/lib/neo4j/conf/neo4j.conf

will be highlighted like a comment beginning with the `#` character. The first characters (especially RUN) are highlighted correctly. So the issue here is that `#` always will be treated like a comment, even when it is used within quotation marks. 

Maybe you could provide an extra highlighting of things within qutation marks, which would fix this issue and add a new nice feature.

```xml
        <context id="string" style-ref="string" end-at-line-end="true">
            <start>L?"</start>
            <end>"</end>
        </context>

        <context id="char" style-ref="string" end-at-line-end="true">
            <start>L?'</start>
            <end>'</end>
        </context>
```

**Comment by ilogue** [comment]
@m007  Excellent, can you make a PR for this?

**Comment by m007** [comment]
@ilogue I'll do my very best :wink: Currently somewhat busy, just give me few days.
