### ISSUE TITLE
Doesn't support gedit 3.10.4

### ISSUE THREAD

**Issue by oferbh** [ilogue/docker.lang#4]
When running gedit on Ubuntu 14.04 I receive the following error:

> 
> /usr/share/gtksourceview-3.0/language-specs/docker.lang:40: parser error : Specification mandate value for attribute data-pjax-transient
>     <meta name="selected-link" value="repo_source" data-pjax-transient>

**Comment by ilogue** [comment]
Try this https://github.com/aggress/riak-zabbix/issues/3#issuecomment-34130199

**Comment by oferbh** [comment]
Thanks, it works now.
